# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
project_name: sing-box-extensions
metadata:
  maintainers:
    - "Lantern Team <dev@getlantern.org>"
  description: Sing Box Extensions
  homepage: "https://github.com/getlantern/lantern-box"
  license: "GPL"

builds:
  - main: ./cmd/sing-box-extensions
    flags:
      - -v
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -X github.com/getlantern/lantern-box/constant.Version={{ .Version }} -s -w -buildid=
    tags:
      - with_gvisor
      - with_quic
      - with_dhcp
      - with_wireguard
      - with_ech
      - with_utls
      - with_reality_server
      - with_clash_api

    binary: sing-box-extensions

archives:
  - formats: ["tar.gz"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  replace_existing_artifacts: true

nfpms:
  - package_name: "sing-box-extensions"
    formats:
      - deb
      - rpm
    section: "default"
    maintainer: "Lantern Team <dev@getlantern.org>"
    description: |
      Sing Box Extensions
    vendor: "Brave New Software"
    homepage: "https://github.com/getlantern/lantern-box"
    license: "GPL"
    contents:
      - src: cmd/sing-box-extensions/release/sing-box-extensions.service
        dst: /usr/lib/systemd/system/sing-box-extensions.service
      - src: cmd/sing-box-extensions/release/sing-box-extensions@.service
        dst: /usr/lib/systemd/system/sing-box-extensions@.service

furies:
  - account: getlantern
    formats:
      - deb
      - rpm

dockers:
  - image_templates:
      - "getlantern/sing-box-extensions:latest"
      - "getlantern/sing-box-extensions:{{ .Tag }}"

dockerhub:
  - images:
      - getlantern/sing-box-extensions
    username: getlantern
    secret_name: DOCKER_PASSWORD
    full_description:
      from_file:
        path: ./README.md
